apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
  labels:
    type: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      type: wiremock
  template:
    metadata:
      labels:
        type: wiremock         
    spec:
      containers:
      - name: wiremock
        image: rbillon59/wiremock-loadtest:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: wiremock-mapping
          mountPath: /home/wiremock/mappings
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"
        livenessProbe:
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__admin
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
        - name: wiremock-mapping
          configMap:
            name: wiremock-mapping
---
apiVersion: v1
kind: Service
metadata:
  name: wiremock-svc
  labels:
    type: wiremock
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    type: wiremock
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-wiremock
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wiremock
  targetCPUUtilizationPercentage: 30